version: "3"

services:

  selenium-hub:
    image: selenium/hub:3.14.0-beryllium
    container_name: selenium-hub
    ports:
    - "4444:4444"

  chrome-linux:
    image: selenium/node-chrome:3.14.0-beryllium
    depends_on:
    - selenium-hub
    environment:
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444

  real-device:
    image: appium/appium
    depends_on:
    - selenium-hub
    privileged: true
    ports:
    - 4723
    volumes:
    - /dev/bus/usb:/dev/bus/usb
    - ~/.android:/root/.android
    environment:
    - CONNECT_TO_GRID=true
    - SELENIUM_HOST=selenium-hub
    - BROWSER_NAME=chrome

  firefox:
    image: selenium/node-firefox:3.14.0-beryllium
    depends_on:
    - selenium-hub
    environment:
    - GRID_MAX_SESSION 5
    - HUB_HOST=selenium-hub
    - HUB_PORT=4444